# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'awsmobilereactnativesample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for awsmobilereactnativesample
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'

  

  platform :ios, '9.0'
  target 'awsmobilereactnativesampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'awsmobilereactnativesample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for awsmobilereactnativesample-tvOS

  target 'awsmobilereactnativesample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
