// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"ws93dml0jd","name":"Todos","description":"","endpoint":"https://ws93dml0jd.execute-api.eu-west-1.amazonaws.com/Development","region":"eu-west-1","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'eu-west-1:fd9ea366-d092-4214-a05e-9ea65824a998',
    'aws_cognito_region': 'eu-west-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'eisenhoweronlinereac-hosting-mobilehub-1054085525',
    'aws_content_delivery_bucket_region': 'eu-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2plag6lo8fqk7.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'eu-west-1',
    'aws_dynamodb_table_schemas': [{"tableName":"eisenhoweronlinereac-mobilehub-1054085525-todos","attributes":[{"name":"userId","type":"S"},{"name":"todoId","type":"S"}],"indexes":[],"region":"eu-west-1","hashKey":"userId","rangeKey":"todoId"}],
    'aws_mobile_analytics_app_id': '75ddb5159b9f4eb693b7f01515898913',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'c07c8d2b-2458-11e8-819f-0b05622f0656',
    'aws_project_name': 'eisenhower-online-react',
    'aws_project_region': 'eu-west-1',
    'aws_resource_bucket_name': 'eisenhoweronlinereac-deployments-mobilehub-1054085525',
    'aws_resource_name_prefix': 'eisenhoweronlinereac-mobilehub-1054085525',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'eisenhoweronlinereac-userfiles-mobilehub-1054085525',
    'aws_user_files_s3_bucket_region': 'eu-west-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'eu-west-1_h9onYdENZ',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '1qr303cmchcr50uln96eukod66',
    'aws_user_settings': 'enable',
}

export default awsmobile;
